title: Hello, world! I'm Mark Kahoush
description: # this means to ignore newlines until "baseurl:"
  Senior computer science student at Georgia Tech with specializations in AI and devices. 
  Interested in internships and research positions in Object-Oriented Software Engineering/Development, 
  Machine Learning and Computer Vision. 
  I'm especially passionate in Software Development and Deep Learning and Computer Vision.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mark Kahoush # add your name
author-img: Image.jfif # add your photo
about-author: I am a computer science major at georgia tech. # add description
social-github: mkahoush # add your Github handle
social-linkedin: mark-kahoush # add your Linkedin handle
social-email: markkahoush@hotmail.com # add your Email address
social-scholar: https://scholar.google.com/citations?hl=en&user=nLm228EAAAAJ 

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
